INFRADEV-11978: Simplify vacuum query
getslash/scotty pull request #36
Opened 2019-02-24 14:53 UTC by DorAmram

Changes the vacuum query from:

SELECT beam.id FROM beam
LEFT JOIN pin ON pin.beam_id = beam.id
LEFT JOIN beam_type ON beam.type_id = beam_type.id
LEFT JOIN file ON file.beam_id = beam.id
WHERE
NOT beam.pending_deletion
AND NOT beam.deleted
AND beam.completed
AND pin.id IS NULL
AND NOT EXISTS (
    SELECT id FROM beam_issues
    INNER JOIN issue ON issue.id = beam_issues.issue_id
    WHERE beam_issues.beam_id = beam.id
    AND issue.open)
AND (
     file.beam_id IS NULL
     OR ((beam.type_id IS NULL) AND (beam.start < now - 'APP.config['VACUUM_THRESHOLD'] days'::interval))
     OR ((beam.type_id IS NOT NULL) AND (beam.start < now - (beam_type.vacuum_threshold * INTERVAL '1 DAY')))))

to:

SELECT beam.id AS beam_id
FROM beam 
LEFT OUTER JOIN pin ON pin.beam_id = beam.id 
LEFT OUTER JOIN beam_type ON beam_type.id = beam.id 
LEFT OUTER JOIN file ON file.beam_id = beam.id                                                         
WHERE 
beam.pending_deletion = 0 
AND beam.deleted = 0 
AND beam.completed = 1 
AND pin.id IS NULL 
AND NOT (EXISTS (SELECT 1                                                                                          
                 FROM beam_issues JOIN issue ON issue.id = beam_issues.issue_id
                 WHERE beam_issues.beam_id = beam.id 
                 AND issue.open = 1)
        ) 
AND file.beam_id IS NULL 
AND trunc(EXTRACT(epoch FROM :param_1) - EXTRACT(epoch FROM beam.start)) / :trunc_1 >= CASE WHEN (beam.type_id IS NULL) THEN :param_2 ELSE beam_type.vacuum_threshold END

2019-05-28 08:18 UTC, r-darwish requested changes

2019-05-28 08:18 UTC, r-darwish commented on flask_app/tasks.py
> +    update(Beam).where(Beam.id.in_(pending_query)).values(pending_deletion='true')
Does `'true'` actually work? It should be `True` 🤔

2019-06-02 07:24 UTC, DorAmram commented on flask_app/tasks.py
> +    update(Beam).where(Beam.id.in_(pending_query)).values(pending_deletion='true')
You're right
Fixed it

2019-09-19 06:51 UTC, drrlvn requested changes

2019-09-19 06:51 UTC, drrlvn commented on flask_app/tasks.py
> +if os.environ.get("SQLALCHEMY_LOG_QUERIES"):
Shouldn't this be somewhere global?

2019-09-19 06:51 UTC, drrlvn commented on flask_app/tasks.py
> +    existing_open_issues = db.session.query(beam_issues.c.beam_id)\
Remove backslashes.

2020-02-26 14:14 UTC, closed without merging

2020-02-26 14:14 UTC, DorAmram commented
Not needed anymore