INFRADEV-12144: Allow sorting file list
getslash/scotty pull request #48
Opened 2019-04-16 08:52 UTC by DorAmram

2019-04-17 05:52 UTC, r-darwish requested changes

2019-04-17 05:52 UTC, r-darwish commented on webapp/app/components/beam-files/component.js
> +      var method = (acsending) ? 'asc': 'desc';
Better use `const` or `let`

https://medium.com/@pandeysoni/when-should-use-const-and-let-instead-of-var-in-javascript-ec2c3d7e5ca6

2019-04-17 05:52 UTC, r-darwish commented on webapp/app/components/beam-files/component.js
> +      this.get('sortKeys').pop()
I think that you don't have to use `this.get` in recent versions of Ember. See if `this.sortKeys.pop()` works.

2019-04-17 05:52 UTC, r-darwish commented on webapp/app/components/sortable-header/component.js
> +    downArrow: '&#9660',
You don't need to put these as variables. Put them directly inside the template.

Also, consider font awesome icons
https://fontawesome.com/icons?d=gallery&q=down

2019-04-17 05:52 UTC, r-darwish commented on webapp/app/components/sortable-header/component.js
> +            this.get('sortBy')(sortProperty, acsending);
I think that you can do `this.sortBy(sortProperties, acsending)`

2019-04-17 05:52 UTC, r-darwish commented on webapp/app/components/sortable-header/component.js
> +        sortBy: function(sortProperty, acsending){
I prefer `sortBy(sortProperty, acsending) {`. No need to use `function`

2019-04-17 05:52 UTC, r-darwish commented on webapp/app/components/sortable-header/component.js
> +import Component from '@ember/component';
Good use of a component 👍

2019-04-17 06:47 UTC, DorAmram commented on webapp/app/components/sortable-header/component.js
> +import Component from '@ember/component';
Thanks :)

2019-05-28 08:13 UTC, r-darwish approved these changes

2019-05-28 08:14 UTC, merged