Damram/infradev 12324
getslash/scotty pull request #53
Opened 2019-05-27 08:16 UTC by DorAmram

2019-05-28 08:09 UTC, r-darwish requested changes

2019-05-28 08:09 UTC, r-darwish commented on Makefile
> +	docker build -t ${IMAGE}:${VERSION} -f docker/Dockerfile . --no-cache=true
Remove `--no-cache`

2019-06-10 06:44 UTC, r-darwish approved these changes

2019-06-10 06:45 UTC, r-darwish requested changes

2019-06-10 06:45 UTC, r-darwish commented on .travis.yml
> +    deploy:
You probably want to do that only when pushing tags or release branches

2019-11-14 08:45 UTC, closed without merging

2019-11-14 08:46 UTC, DorAmram commented
Superseded by INFRADEDV-13092