INFRADEV-13092: Move to github actions
getslash/scotty pull request #90
Opened 2019-11-28 12:56 UTC by DorAmram

2019-12-10 13:46 UTC, drrlvn commented on .github/workflows/combadge-workflow.yml
> +      - working-directory: transporter
Shouldn't this be indented?

2020-01-05 15:19 UTC, gleon99 requested changes

2020-01-05 15:19 UTC, gleon99 commented on .github/workflows/continuous-integration-workflow.yml
> +on: [push]
`on: push`

2020-01-05 15:19 UTC, gleon99 commented on .github/workflows/docker-workflow.yml
> +      run: cargo build
Why not `--release` ?

2020-01-05 15:19 UTC, gleon99 commented on .github/workflows/docker-workflow.yml
> +          test_command: cargo test
There're no tests. Why this command is needed?

2020-01-05 15:19 UTC, gleon99 commented on .github/workflows/docker-workflow.yml
> +  build_transporter:
There's no `clippy` step here (unlike combadge) - is that intentional?

2020-01-05 15:19 UTC, gleon99 commented on .github/workflows/continuous-integration-workflow.yml
> +    - uses: actions/setup-python@v1
Maybe specify Python version here?

2020-01-05 15:19 UTC, gleon99 commented on .github/workflows/docker-workflow.yml
> +        COMBADGE_DIR: combadge_assets
Maybe I'm missing something?
I see stuff copied *from* this directory (`combadge_assets`) in Dockerfile.
But when does anything being placed there?

2020-01-06 08:56 UTC, DorAmram commented on .github/workflows/docker-workflow.yml
> +          test_command: cargo test
I want the building to be quick in case of failures.
In the future there will be tests added

2020-01-06 08:59 UTC, DorAmram commented on .github/workflows/continuous-integration-workflow.yml
> +    - uses: actions/setup-python@v1
I want the latest python version here and not to lock it to a certain version

2020-01-08 09:36 UTC, merged